name: ecomm_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animations: ^2.0.11
  bottom_navy_bar: ^6.1.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_cart: ^0.0.9
  
  flutter_login: ^5.0.0
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^11.0.0
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  onesignal_flutter: ^5.2.4
  provider: ^6.1.2
  razorpay_flutter: ^1.3.7
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.9.0
  iconsax: ^0.0.8
  gap: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

